var a;function UIComponent(){}UIComponent.prototype.getPosition=function(){return HtmlUtil.getCoords(this.getUI())};UIComponent.prototype.getUI=function(){return this.ui};
function TaskNode(b,c,f,h){this.id=h;this.container=f;this.componentType=Constants.COMPONENT_TYPE_NODE;this.ui=HtmlUtil.newElement('<div onselectstart="javascript:return false;" style="position:absolute;z-index:5;" class="workflow-node"></div>');this.beginLine=[];this.endLine=[];this.beginPolyLine=[];this.endPolyLine=[];this.beforeNode=[];this.nextNode=[];this.canDrop=this.canDrag=true;HtmlUtil.setWidth(this.getUI(),b);HtmlUtil.setHeight(this.getUI(),c);this.rectDiv_top=new RectZone(this,Constants.RectZone_TOP,
50,10);HtmlUtil.setLeft(this.rectDiv_top.getUI(),Math.round(b/2)-Math.round(this.rectDiv_top.w/2)+"px");HtmlUtil.setTop(this.rectDiv_top.getUI(),"0px");this.rectDiv_left=new RectZone(this,Constants.RectZone_LEFT,10,20);HtmlUtil.setLeft(this.rectDiv_left.getUI(),"0px");HtmlUtil.setTop(this.rectDiv_left.getUI(),Math.round(c/2)-Math.round(this.rectDiv_left.h/2)+"px");this.rectDiv_right=new RectZone(this,Constants.RectZone_RIGHT,10,20);HtmlUtil.setRight(this.rectDiv_right.getUI(),"0px");HtmlUtil.setTop(this.rectDiv_right.getUI(),
Math.round(c/2)-Math.round(this.rectDiv_right.h/2)+"px");this.rectDiv_bottom=new RectZone(this,Constants.RectZone_BOTTOM,50,10);HtmlUtil.setLeft(this.rectDiv_bottom.getUI(),Math.round(b/2)-Math.round(this.rectDiv_bottom.w/2)+"px");HtmlUtil.setBottom(this.rectDiv_bottom.getUI(),"0px");HtmlUtil.append(this.getUI(),this.rectDiv_top.getUI());HtmlUtil.append(this.getUI(),this.rectDiv_left.getUI());HtmlUtil.append(this.getUI(),this.rectDiv_right.getUI());HtmlUtil.append(this.getUI(),this.rectDiv_bottom.getUI());
b=new NodeContent(f.operationMode,"node"+h);HtmlUtil.append(this.getUI(),b.getUI());this.removeUI=function(){HtmlUtil.remove(this.getUI());this.rectDiv_bottom=this.rectDiv_right=this.rectDiv_left=this.rectDiv_top=null;for(var d=0,e=this.beginLine.length;d<e;d++){var i=this.beginLine[d];this.container.deleteComponent(i)}d=0;for(e=this.endLine.length;d<e;d++){i=this.endLine[d];this.container.deleteComponent(i)}d=0;for(e=this.beginPolyLine.length;d<e;d++){i=this.beginPolyLine[d];this.container.deleteComponent(i)}d=
0;for(e=this.endPolyLine.length;d<e;d++){i=this.endPolyLine[d];this.container.deleteComponent(i)}d=0;for(e=this.beforeNode.length;d<e;d++){i=this.beforeNode[d];i.nextNode.removeObj(this)}d=0;for(e=this.nextNode.length;d<e;d++){i=this.nextNode[d];i.beforeNode.removeObj(this)}};this.canAddLine=function(d){if(d==this)return false;if(this.addBeforeNode(d)){d.addNextNode(this);return true}else return false};new NodeListener(this)}TaskNode.prototype=new UIComponent;
TaskNode.prototype.showController=function(){HtmlUtil.addClass(this.getUI(),"node-selected")};TaskNode.prototype.hideController=function(){HtmlUtil.removeClass(this.getUI(),"node-selected")};TaskNode.prototype.addBeforeNode=function(b){if(this.beforeNode.indexOf(b)==-1){this.beforeNode.push(b);return true}else return false};TaskNode.prototype.addNextNode=function(b){if(this.nextNode.indexOf(b)==-1){this.nextNode.push(b);return true}else return false};
function NodeListener(b){function c(j){g.unSelectAll();g.currentSelectedComponent=b;b.showController();j.stopPropagation()}function f(j){if(b.container.operationMode==Constants.BTN_LINE_TYPE||b.container.operationMode==Constants.BTN_POLYLINE_TYPE){HtmlUtil.show(b.rectDiv_top.getUI());HtmlUtil.show(b.rectDiv_left.getUI());HtmlUtil.show(b.rectDiv_right.getUI());HtmlUtil.show(b.rectDiv_bottom.getUI())}j.stopPropagation()}function h(j){if(b.container.operationMode==Constants.BTN_LINE_TYPE||b.container.operationMode==
Constants.BTN_POLYLINE_TYPE){HtmlUtil.hide(b.rectDiv_top.getUI());HtmlUtil.hide(b.rectDiv_left.getUI());HtmlUtil.hide(b.rectDiv_right.getUI());j.stopPropagation();HtmlUtil.hide(b.rectDiv_bottom.getUI())}j.stopPropagation()}function d(j){j=j||window.event;var l=HtmlUtil.mouseCoords(j),o=Math.max(l.y-k.y-m.y,0);HtmlUtil.setTop(b.getUI(),o+"px");l=Math.max(l.x-k.x-m.x,0);HtmlUtil.setLeft(b.getUI(),l+"px");for(var n=0,r=b.beginLine.length;n<r;n++){var p=b.beginLine[n],q=p.beginPosOffset;p.setFrom(q.x+
l,q.y+o)}n=0;for(r=b.endLine.length;n<r;n++){p=b.endLine[n];q=p.endPosOffset;p.setTo(q.x+l,q.y+o)}n=0;for(r=b.beginPolyLine.length;n<r;n++){p=b.beginPolyLine[n];q=p.beginPosOffset;p.setFrom(q.x+l,q.y+o)}n=0;for(r=b.endPolyLine.length;n<r;n++){p=b.endPolyLine[n];q=p.endPosOffset;p.setTo(q.x+l,q.y+o)}j.stopPropagation()}function e(j){g.unSelectAll();g.currentSelectedComponent=b;b.showController();if(g.operationMode==Constants.BTN_SELECT_TYPE||g.operationMode==Constants.BTN_NODE_TYPE){$(b.getUI()).bind("mousemove",
d);$(b.getUI()).bind("mouseup",i);k=HtmlUtil.getMouseOffset(b.getUI(),j);b.getUI().setCapture()}else{$(b.getUI()).unbind("mousemove",d);$(b.getUI()).unbind("mouseup",i)}}function i(j){for(var l=0,o=b.beginLine.length;l<o;l++){var n=b.beginLine[l];n.setControllerPosition()}l=0;for(o=b.endLine.length;l<o;l++){n=b.endLine[l];n.setControllerPosition()}l=0;for(o=b.beginPolyLine.length;l<o;l++){n=b.beginPolyLine[l];n.setControllerPosition()}l=0;for(o=b.endPolyLine.length;l<o;l++){n=b.endPolyLine[l];n.setControllerPosition()}$(b.getUI()).unbind("mousemove",
d);$(b.getUI()).unbind("mouseup",i);j.stopPropagation();b.getUI().releaseCapture()}var k,g=b.container,m=g.getPosition();$(b.getUI()).bind("mousedown",e);$(b.getUI()).bind("mouseover",f);$(b.getUI()).bind("mouseout",h);$(b.getUI()).bind("click",c)}
function NodeContent(b,c){this.ui=HtmlUtil.newElement('<table  cellspacing=0 cellpadding=0  border=0><tr class="title"><td align=middle valign="middle" width="20%"><div class="'+b+'" style="width:16px;height:16px;margin-right:5px"></div></td><td class=txt align=middle valign="middle">'+c+"</td></tr></table>")}NodeContent.prototype=new UIComponent;
function RectZone(b,c,f,h){this.node=b;this.type=c;this.w=f;this.h=h;this.ui=HtmlUtil.newElement('<div onselectstart="javascript:return false;" class="rect-zone" style="position:absolute;z-index:6;display:none;"></div>');HtmlUtil.setWidth(this.getUI(),this.w);HtmlUtil.setHeight(this.getUI(),this.h);this.getEdgePos=function(d,e){e=e.getPosition();var i=this.getPosition(),k={x:0,y:0};switch(this.type){case Constants.RectZone_TOP:k.x=d.x-e.x;k.y=i.y-e.y-1;break;case Constants.RectZone_RIGHT:k.x=i.x-
e.x+this.w;k.y=d.y-e.y;break;case Constants.RectZone_BOTTOM:k.x=d.x-e.x;k.y=i.y-e.y+this.h;break;case Constants.RectZone_LEFT:k.x=i.x-e.x-1;k.y=d.y-e.y;break}return k};this.addBeginLine=function(d){this.node.beginLine.push(d)};this.addEndLine=function(d){this.node.endLine.push(d)};this.addBeginPolyLine=function(d){this.node.beginPolyLine.push(d)};this.addEndPolyLine=function(d){this.node.endPolyLine.push(d)};this.getMiddlePoints=function(d,e){return this.type==Constants.RectZone_TOP||this.type==Constants.RectZone_BOTTOM?
{x:parseInt(d.x,10),y:parseInt(e.y,10)}:{x:parseInt(e.x,10),y:parseInt(d.y,10)}};new RectZoneListener(this)}RectZone.prototype=new UIComponent;function RectZoneListener(b){function c(){if(h.startDraw){if(b.node.canDrop)h.toNode=b}else if(b.node.canDrag)h.fromNode=b}function f(){if(h.startDraw)h.toNode=null;else h.fromNode=null}var h=b.node.container;$(b.getUI()).bind("mouseover",c);$(b.getUI()).bind("mouseout",f)}
function Container(){this.id=1;this.operationMode=Constants.BTN_NODE_TYPE;this.toNode=this.fromNode=null;this.startDraw=false;this.ui=HtmlUtil.newElement('<div onselectstart="javascript:return false;" class="workflow-container" style="position:relative;top:35px;"></div>');this.lines=[];this.nodes=[];this.polyLines=[];this.addNode=function(b,c){var f=this.getPosition();HtmlUtil.setLeft(b.getUI(),c.x-f.x+"px");HtmlUtil.setTop(b.getUI(),c.y-f.y+"px");HtmlUtil.prepend(this.getUI(),b.getUI());this.nodes.push(b)};
this.addLine=function(b,c){var f=this.fromNode.node.getPosition(),h=this.getPosition(),d=container.fromNode.getEdgePos(c,container);b.setFrom(d.x,d.y);b.setTo(d.x,d.y);b.beginPosOffset={x:d.x-f.x+h.x,y:d.y-f.y+h.y};HtmlUtil.prepend(this.getUI(),b.getUI());this.lines.push(b);return{x:c.x,y:c.y}};this.addPolyLine=function(b){HtmlUtil.prepend(this.getUI(),b.getUI());this.polyLines.push(b)};this.deleteComponent=function(b){if(b){b.removeUI();switch(b.componentType){case Constants.COMPONENT_TYPE_LINE:this.lines.removeObj(b);
break;case Constants.COMPONENT_TYPE_NODE:this.nodes.removeObj(b);break;case Constants.COMPONENT_TYPE_POLYLINE:this.polyLines.removeObj(b);break}}};this.unSelectAll=function(){this.currentSelectedComponent=null;for(var b=0,c=this.lines.length;b<c;b++)this.lines[b].hideController();b=0;for(c=this.nodes.length;b<c;b++)this.nodes[b].hideController();b=0;for(c=this.polyLines.length;b<c;b++)this.polyLines[b].hideController()};new ContainerListener(this)}Container.prototype=new UIComponent;
function ContainerListener(b){function c(g){g=HtmlUtil.mouseCoords(g);b.unSelectAll();switch(b.operationMode){case Constants.BTN_SELECT_TYPE:break;case Constants.BTN_NODE_TYPE:var m=new TaskNode(100,40,b,b.id);b.id++;b.addNode(m,g);break;case Constants.BTN_STARTNODE_TYPE:m=new StartNode(100,40,b,b.id);b.id++;b.addNode(m,g);break;case Constants.BTN_ENDNODE_TYPE:m=new EndNode(100,40,b,b.id);b.id++;b.addNode(m,g);break;case Constants.BTN_LINE_TYPE:break}}function f(g){if(b.operationMode==Constants.BTN_LINE_TYPE||
b.operationMode==Constants.BTN_POLYLINE_TYPE)if(b.fromNode!=null){e=new Line(b,b.id);b.id++;g=HtmlUtil.mouseCoords(g);k=b.addLine(e,g);b.startDraw=true;$(b.getUI()).bind("mousemove",h);$(b.getUI()).bind("mouseup",d);i=b.getPosition()}}function h(g){g=g||window.event;g=HtmlUtil.mouseCoords(g);g.x<=k.x?e.setTo(g.x-i.x+3,g.y-i.y+2):e.setTo(g.x-i.x-3,g.y-i.y-2)}function d(g){g=g||window.event;var m=HtmlUtil.mouseCoords(g);if(b.toNode==null||!b.toNode.node.canAddLine(b.fromNode.node))b.deleteComponent(e);
else{m=b.toNode.getEdgePos(m,b);e.setTo(m.x,m.y);var j=b.toNode.node.getPosition(),l=b.getPosition();e.endPosOffset={x:m.x-(j.x-l.x),y:m.y-(j.y-l.y)};if(b.operationMode==Constants.BTN_LINE_TYPE){e.finishLine();b.fromNode.addBeginLine(e);b.toNode.addEndLine(e);e.beginNode=b.fromNode.node;e.endNode=b.toNode.node}if(b.operationMode==Constants.BTN_POLYLINE_TYPE){m=b.fromNode.getMiddlePoints(e.getFrom(),e.getTo());j=new PolyLine(b,b.id);b.id++;b.addPolyLine(j);j.setFrom(e.getFrom().x,e.getFrom().y);j.setTo(e.getTo().x,
e.getTo().y);j.setMiddle(m.x,m.y);j.beginPosOffset=e.beginPosOffset;j.endPosOffset=e.endPosOffset;j.finishLine();j.addController(b);b.deleteComponent(e);b.fromNode.addBeginPolyLine(j);b.toNode.addEndPolyLine(j);j.beginNode=b.fromNode.node;j.endNode=b.toNode.node}}$(b.getUI()).unbind("mousemove");$(b.getUI()).unbind("mouseup");b.toNode=null;b.fromNode=null;b.startDraw=false;g.stopPropagation()}var e,i,k;$(b.getUI()).bind("click",c);$(b.getUI()).bind("mousedown",f)}
function Line(b,c){this.id=c;this.componentType=Constants.COMPONENT_TYPE_LINE;this.container=b;this.ui=HtmlUtil.newElement('<v:line style="position:absolute;z-index:11;"></v:line>');this.arrow=HtmlUtil.newElement('<v:Stroke dashstyle="solid" endarrow="classic"/>');this.setControllerPosition=function(){if(this.beginController&&this.endController)switch(Line._getDirection(this.getFrom(),this.getTo())){case Constants.DIRECTION_LT:HtmlUtil.setLeft(this.endController.getUI(),"0px");HtmlUtil.setTop(this.endController.getUI(),
"0px");HtmlUtil.setLeft(this.beginController.getUI(),Math.abs(this.getFrom().x-this.getTo().x)+"px");HtmlUtil.setTop(this.beginController.getUI(),Math.abs(this.getFrom().y-this.getTo().y)+"px");break;case Constants.DIRECTION_RT:HtmlUtil.setLeft(this.beginController.getUI(),"0px");HtmlUtil.setTop(this.beginController.getUI(),Math.abs(this.getFrom().y-this.getTo().y)+"px");HtmlUtil.setLeft(this.endController.getUI(),Math.abs(this.getFrom().x-this.getTo().x)+"px");HtmlUtil.setTop(this.endController.getUI(),
"0px");break;case Constants.DIRECTION_LB:HtmlUtil.setLeft(this.endController.getUI(),"0px");HtmlUtil.setTop(this.endController.getUI(),Math.abs(this.getFrom().y-this.getTo().y)+"px");HtmlUtil.setLeft(this.beginController.getUI(),Math.abs(this.getFrom().x-this.getTo().x)+"px");HtmlUtil.setTop(this.beginController.getUI(),"0px");break;case Constants.DIRECTION_RB:HtmlUtil.setLeft(this.beginController.getUI(),"0px");HtmlUtil.setTop(this.beginController.getUI(),"0px");HtmlUtil.setLeft(this.endController.getUI(),
Math.abs(this.getFrom().x-this.getTo().x)+"px");HtmlUtil.setTop(this.endController.getUI(),Math.abs(this.getFrom().y-this.getTo().y)+"px");break}};new LineListener(this)}Line.prototype=new UIComponent;a=Line.prototype;a.setFrom=function(b,c){this.fromPos={x:parseInt(b,10),y:parseInt(c,10)};this.getUI().from=b+","+c};a.getFrom=function(){return this.fromPos};a.setTo=function(b,c){this.toPos={x:parseInt(b,10),y:parseInt(c,10)};this.getUI().to=b+","+c};a.getTo=function(){return this.toPos};
a.showController=function(){HtmlUtil.show(this.beginController.getUI());HtmlUtil.show(this.endController.getUI())};a.hideController=function(){HtmlUtil.hide(this.beginController.getUI());HtmlUtil.hide(this.endController.getUI())};a.removeUI=function(){HtmlUtil.remove(this.getUI());if(this.beginNode){this.beginNode.beginLine.removeObj(this);this.beginNode.nextNode.removeObj(this.endNode)}if(this.endNode){this.endNode.endLine.removeObj(this);this.endNode.beforeNode.removeObj(this.beginNode)}};
a.finishLine=function(){HtmlUtil.append(this.getUI(),this.arrow);this.beginController=new LineController(this.container,this,5,5);this.endController=new LineController(this.container,this,5,5);HtmlUtil.append(this.getUI(),this.beginController.getUI());HtmlUtil.append(this.getUI(),this.endController.getUI());this.setControllerPosition()};
Line._getDirection=function(b,c){if(c.x>=b.x&&c.y<=b.y)return Constants.DIRECTION_RT;if(c.x>=b.x&&c.y>=b.y)return Constants.DIRECTION_RB;if(c.x<b.x&&c.y<b.y)return Constants.DIRECTION_LT;if(c.x<b.x&&c.y>b.y)return Constants.DIRECTION_LB};
function LineController(b,c,f,h){this.line=c;this.w=f;this.h=h;this.container=b;this.ui=HtmlUtil.newElement('<div onselectstart="javascript:return false;" class="controller-zone" style="position:absolute;z-index:12;display:none;"></div>');this.getUI=function(){return this.ui};HtmlUtil.setWidth(this.getUI(),this.w);HtmlUtil.setHeight(this.getUI(),this.h);this.getPosition=function(){return HtmlUtil.getCoords(this.getUI())}}
function LineListener(b){$(b.getUI()).bind("click",function(c){b.container.unSelectAll();b.container.currentSelectedComponent=b;b.showController();c.stopPropagation()})}
function PolyLine(b,c){Line.call(this,b,c);this.componentType=Constants.COMPONENT_TYPE_POLYLINE;this.ui=HtmlUtil.newElement('<v:polyline filled="false" style="position:absolute;z-index:11;"></v:polyline>');this.arrow=HtmlUtil.newElement('<v:Stroke dashstyle="solid" endarrow="classic"/>');this.setFrom=function(f,h){this.fromPos=f+","+h;this.getUI().points.value=this.fromPos+" "+this.middlePos+" "+this.toPos};this.getFrom=function(){var f=this.fromPos.split(",");return{x:parseInt(f[0],10),y:parseInt(f[1],
10)}};this.setMiddle=function(f,h){this.middlePos=f+","+h;this.getUI().points.value=this.fromPos+" "+this.middlePos+" "+this.toPos};this.getMiddle=function(){var f=this.middlePos.split(",");return{x:parseInt(f[0],10),y:parseInt(f[1],10)}};this.setTo=function(f,h){this.toPos=f+","+h;this.getUI().points.value=this.fromPos+" "+this.middlePos+" "+this.toPos};this.getTo=function(){var f=this.toPos.split(",");return{x:parseInt(f[0],10),y:parseInt(f[1],10)}};this.addController=function(f){this.controller=
new PolyLineController(f,this,5,5);HtmlUtil.setLeft(this.controller.getUI(),this.getMiddle().x-Math.round(this.controller.w/2)+"px");HtmlUtil.setTop(this.controller.getUI(),this.getMiddle().y-Math.round(this.controller.h/2)+"px");HtmlUtil.after(this.getUI(),this.controller.getUI())};this.removeUI=function(){HtmlUtil.remove(this.getUI());HtmlUtil.remove(this.controller.getUI());this.controller=null;if(this.beginNode){this.beginNode.beginPolyLine.removeObj(this);this.beginNode.nextNode.removeObj(this.endNode)}if(this.endNode){this.endNode.endPolyLine.removeObj(this);
this.endNode.beforeNode.removeObj(this.beginNode)}};new LineListener(this)}PolyLine.prototype=new Line;function PolyLineController(b,c,f,h){this.pline=c;this.w=f;this.h=h;this.container=b;this.ui=HtmlUtil.newElement('<div onselectstart="javascript:return false;" class="rect-zone" style="position:absolute;z-index:12;"></div>');HtmlUtil.setWidth(this.getUI(),this.w);HtmlUtil.setHeight(this.getUI(),this.h);new PolyLineControllerListener(this)}PolyLineController.prototype=new UIComponent;
function PolyLineControllerListener(b){function c(k){k=k||window.event;var g=HtmlUtil.mouseCoords(k),m=Math.max(g.y-d.y-i.y,0);HtmlUtil.setTop(b.getUI(),m+"px");g=Math.max(g.x-d.x-i.x,0);HtmlUtil.setLeft(b.getUI(),g+"px");b.pline.setMiddle(g,m);k.stopPropagation()}function f(k){if(e.operationMode==Constants.BTN_SELECT_TYPE){$(b.getUI()).bind("mousemove",c);$(b.getUI()).bind("mouseup",h);d=HtmlUtil.getMouseOffset(b.getUI(),k);b.getUI().setCapture()}else{$(b.getUI()).unbind("mousemove",c);$(b.getUI()).unbind("mouseup",
h)}k.stopPropagation()}function h(k){$(b.getUI()).unbind("mousemove",c);$(b.getUI()).unbind("mouseup",h);k.stopPropagation();b.getUI().releaseCapture()}var d,e=b.container,i=e.getPosition();$(b.getUI()).bind("mousedown",f)}function StartNode(b,c,f,h){TaskNode.call(this,b,c,f,h);this.canDrop=false}StartNode.prototype=TaskNode.prototype;function EndNode(b,c,f,h){TaskNode.call(this,b,c,f,h);this.canDrag=false}EndNode.prototype=TaskNode.prototype;
function Button(b,c){this.toolbar=b;this.type=c;this.ui=HtmlUtil.newElement('<div class="workflow-btn '+c+'" style="position:absolute;"></div>');new ButtonListener(this)}Button.prototype=new UIComponent;Button.prototype.setLeft=function(b){HtmlUtil.setLeft(this.getUI(),b)};Button.prototype.setTop=function(b){HtmlUtil.setTop(this.getUI(),b)};Button.prototype.setPressed=function(){HtmlUtil.addClass(this.getUI(),"pressed")};
Button.prototype.cancelPressed=function(){HtmlUtil.removeClass(this.getUI(),"pressed")};function ButtonListener(b){$(b.getUI()).bind("click",function(){b.toolbar.setPressed(b.type);b.setPressed()})}function DeleteButton(b){this.toolbar=b;this.type=Constants.BTN_DELETE_TYPE;this.ui=HtmlUtil.newElement('<div class="workflow-btn '+this.type+'" style="position:absolute;"></div>');new DelButtonListener(this)}DeleteButton.prototype=Button.prototype;
function DelButtonListener(b){$(b.getUI()).bind("mousedown",function(){b.setPressed()});$(b.getUI()).bind("mouseup",function(){b.cancelPressed();var c=b.toolbar.container;c.deleteComponent(c.currentSelectedComponent)})}
function ToolBar(b){this.ui=HtmlUtil.newElement('<div class="workflow-toolbar" style="position:absolute;"></div>');this.container=b;var c=[];b=new Button(this,Constants.BTN_SELECT_TYPE);b.setTop("5px");b.setLeft("2px");c.push(b);var f=new Button(this,Constants.BTN_LINE_TYPE);f.setTop("5px");f.setLeft("27px");c.push(f);var h=new Button(this,Constants.BTN_POLYLINE_TYPE);h.setTop("5px");h.setLeft("52px");c.push(h);var d=new Button(this,Constants.BTN_NODE_TYPE);d.setTop("5px");d.setLeft("77px");c.push(d);
var e=new Button(this,Constants.BTN_STARTNODE_TYPE);e.setTop("5px");e.setLeft("102px");c.push(e);var i=new Button(this,Constants.BTN_ENDNODE_TYPE);i.setTop("5px");i.setLeft("127px");c.push(i);var k=new DeleteButton(this);k.setTop("5px");k.setLeft("152px");c.push(k);HtmlUtil.append(this.getUI(),b.getUI());HtmlUtil.append(this.getUI(),f.getUI());HtmlUtil.append(this.getUI(),h.getUI());HtmlUtil.append(this.getUI(),d.getUI());HtmlUtil.append(this.getUI(),e.getUI());HtmlUtil.append(this.getUI(),i.getUI());
HtmlUtil.append(this.getUI(),k.getUI());this.setPressed=function(g){this.container.operationMode=g;if(this.container.operationMode==Constants.BTN_POLYLINE_TYPE||this.container.operationMode==Constants.BTN_LINE_TYPE)$(this.container.getUI()).get(0).style.cursor="crosshair";else $(this.container.getUI()).get(0).style.cursor="default";g=0;for(var m=c.length;g<m;g++)c[g].cancelPressed()}}ToolBar.prototype=new UIComponent;
